### ISSUE TITLE
Update source on https://pkgs.racket-lang.org/package/fixw

### ISSUE THREAD

**Issue by sorawee** [6cdh/racket-fixw#2]
Right now, the source is pinned to the commit a48b3fe4ade1c79c4025e2e8992feae0f9a6796f. It would be nice to either unpin it or update it to the latest version.

In the upcoming release, Racket will check version numbers, so without https://github.com/6cdh/racket-fixw/commit/66b0a4648835068a215119789e1fad3d30ce840c, the package server will report a dep issue on the package (see e.g. https://plt.cs.northwestern.edu/release-pkg-build/server/built/deps/fixw.txt)

**Comment by 6cdh** [comment]
updated. Thanks.

**Comment by sorawee** [comment]
Thanks!
